name: Deploy

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Update based on your requirements

      # Step 3: Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm ci # Faster and ensures a clean install
          npm run build

      # Step 4: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist  # Update to your build output folder

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Depends on the build job

    steps:
      # Step 1: Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update with your region  # Update to your AWS region

      # Step 3: Setup Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.2

      # Step 4: Deploy infrastructure using Terraform
      - name: Deploy IaC with Terraform
        run: |
          terraform init
          terraform apply -auto-approve

      # Step 5: Sync website files to S3
      - name: Sync website files to S3
        run: |
          aws s3 sync ./dist s3://alandis-website --delete

      # Step 6: Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id EPT6AM87ACQE3 --paths "/*"

  smoke-test:
    runs-on: ubuntu-latest
    needs: deploy  # Depends on the deploy job

    steps:
      # Step 1: Install Cypress dependencies
      - name: Install Cypress dependencies
        run: |
          npm ci # Ensures a clean install
          npm install cypress

      # Step 2: Run Cypress smoke tests
      - name: Run Cypress smoke tests
        run: |
          npx cypress run
